//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chambers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affliction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Affliction()
        {
            this.CharacterAfflictions = new HashSet<CharacterAffliction>();
        }
    
        public int AfflicationId { get; set; }
        public string Name { get; set; }
        public int NumStages { get; set; }
        public bool IsAdvancedIllness { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterAffliction> CharacterAfflictions { get; set; }
    }
}
