//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chambers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affliction
    {
        public int AfflicationId { get; set; }
        public string Name { get; set; }
        public int NumStages { get; set; }
        public bool IsAdvancedIllness { get; set; }
    
        public virtual CharacterAffliction CharacterAffliction { get; set; }
    }
}
